pool:
  vmImage: ubuntu-18.04

variables:
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
  configuration: Release
  tagged: $[ startsWith(variables['Build.SourceBranch'], 'refs/tags') ]
  project: SourceEngine.Demo.Parser

jobs:
  - job: build
    displayName: 'Build & Deploy'
    steps:
      - template: ci/build.yml
      - template: ci/deploy.yml
