steps:
  - task: Cache@2
    displayName: 'Restore package cache'
    inputs:
      key: 'nuget | "$(Agent.OS)" | **/packages.lock.json'
      restoreKeys: |
        nuget | "$(Agent.OS)"
        nuget
      path: $(NUGET_PACKAGES)
    enabled: false

  - script: dotnet restore "${PROJECT}.sln" -p:RestoreLockedMode=true
    displayName: 'Restore packages'

  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      command: build
      projects: $(project).sln
      configuration: $(configuration)
      arguments: --no-restore

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: test
      projects: 'tests/*/*.csproj'
      configuration: $(configuration)
      publishTestResults: true
      nobuild: true

  - task: PublishTestResults@2
    displayName: 'Publish test results'
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      searchFolder: $(Agent.TempDirectory)
